# Parkinson Disease Classification

In [0]:
import pandas as pd

In [0]:
df=pd.read_csv('drive/My Drive/ReplicatedAcousticFeatures-ParkinsonDatabase.csv')

## Data Summary

In [21]:
df.head()

ID  Recording  Status  Gender  ...    Delta9   Delta10   Delta11   Delta12
0  CONT-01          1       0       1  ...  1.403678  1.405495  1.416705  1.354610
1  CONT-01          2       0       1  ...  1.322870  1.314549  1.318999  1.323508
2  CONT-01          3       0       1  ...  1.438053  1.388910  1.305469  1.305402
3  CONT-02          1       0       0  ...  1.551286  1.638346  1.604008  1.621456
4  CONT-02          2       0       0  ...  1.640088  1.533666  1.297536  1.382023

[5 rows x 48 columns]

In [22]:
df.isna().head()

ID  Recording  Status  Gender  ...  Delta9  Delta10  Delta11  Delta12
0  False      False   False   False  ...   False    False    False    False
1  False      False   False   False  ...   False    False    False    False
2  False      False   False   False  ...   False    False    False    False
3  False      False   False   False  ...   False    False    False    False
4  False      False   False   False  ...   False    False    False    False

[5 rows x 48 columns]

In [23]:
df.shape

(240, 48)

In [24]:
df.describe

<bound method NDFrame.describe of           ID  Recording  Status  Gender  ...    Delta9   Delta10   Delta11   Delta12
0    CONT-01          1       0       1  ...  1.403678  1.405495  1.416705  1.354610
1    CONT-01          2       0       1  ...  1.322870  1.314549  1.318999  1.323508
2    CONT-01          3       0       1  ...  1.438053  1.388910  1.305469  1.305402
3    CONT-02          1       0       0  ...  1.551286  1.638346  1.604008  1.621456
4    CONT-02          2       0       0  ...  1.640088  1.533666  1.297536  1.382023
5    CONT-02          3       0       0  ...  1.625396  1.651655  1.652845  1.427623
6    CONT-03          1       0       1  ...  1.345959  1.741863  1.828781  1.655604
7    CONT-03          2       0       1  ...  1.526714  1.647910  1.662981  1.609652
8    CONT-03          3       0       1  ...  1.447470  1.354798  1.585025  1.334293
9    CONT-04          1       0       1  ...  1.579521  1.374581  1.550638  1.572821
10   CONT-04          2       0

In [25]:
df.isnull().sum()

ID            0
Recording     0
Status        0
Gender        0
Jitter_rel    0
Jitter_abs    0
Jitter_RAP    0
Jitter_PPQ    0
Shim_loc      0
Shim_dB       0
Shim_APQ3     0
Shim_APQ5     0
Shi_APQ11     0
HNR05         0
HNR15         0
HNR25         0
HNR35         0
HNR38         0
RPDE          0
DFA           0
PPE           0
GNE           0
MFCC0         0
MFCC1         0
MFCC2         0
MFCC3         0
MFCC4         0
MFCC5         0
MFCC6         0
MFCC7         0
MFCC8         0
MFCC9         0
MFCC10        0
MFCC11        0
MFCC12        0
Delta0        0
Delta1        0
Delta2        0
Delta3        0
Delta4        0
Delta5        0
Delta6        0
Delta7        0
Delta8        0
Delta9        0
Delta10       0
Delta11       0
Delta12       0
dtype: int64

In [26]:
df.isna().sum()

ID            0
Recording     0
Status        0
Gender        0
Jitter_rel    0
Jitter_abs    0
Jitter_RAP    0
Jitter_PPQ    0
Shim_loc      0
Shim_dB       0
Shim_APQ3     0
Shim_APQ5     0
Shi_APQ11     0
HNR05         0
HNR15         0
HNR25         0
HNR35         0
HNR38         0
RPDE          0
DFA           0
PPE           0
GNE           0
MFCC0         0
MFCC1         0
MFCC2         0
MFCC3         0
MFCC4         0
MFCC5         0
MFCC6         0
MFCC7         0
MFCC8         0
MFCC9         0
MFCC10        0
MFCC11        0
MFCC12        0
Delta0        0
Delta1        0
Delta2        0
Delta3        0
Delta4        0
Delta5        0
Delta6        0
Delta7        0
Delta8        0
Delta9        0
Delta10       0
Delta11       0
Delta12       0
dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 48 columns):
ID            240 non-null object
Recording     240 non-null int64
Status        240 non-null int64
Gender        240 non-null int64
Jitter_rel    240 non-null float64
Jitter_abs    240 non-null float64
Jitter_RAP    240 non-null float64
Jitter_PPQ    240 non-null float64
Shim_loc      240 non-null float64
Shim_dB       240 non-null float64
Shim_APQ3     240 non-null float64
Shim_APQ5     240 non-null float64
Shi_APQ11     240 non-null float64
HNR05         240 non-null float64
HNR15         240 non-null float64
HNR25         240 non-null float64
HNR35         240 non-null float64
HNR38         240 non-null float64
RPDE          240 non-null float64
DFA           240 non-null float64
PPE           240 non-null float64
GNE           240 non-null float64
MFCC0         240 non-null float64
MFCC1         240 non-null float64
MFCC2         240 non-null float64
MFCC3         240 non-null 

## Importing functions

In [0]:
    import numpy as np
    import pandas as pd
    import os, sys
    from sklearn.preprocessing import MinMaxScaler
    from xgboost import XGBClassifier
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score

## Data Pre-processing

In [0]:
features=df.loc[:,df.columns!='Status'].values[:,1:]
labels=df.loc[:,'Status'].values

In [30]:
print(labels[labels==1].shape[0], labels[labels==0].shape[0])

120 120


## Scale the Column Values

In [0]:
scaler=MinMaxScaler((-1,1))
x=scaler.fit_transform(features)
y=labels

## Split the train and test data

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=7)

In [33]:
y_test.shape

(48,)

In [34]:
y_train.shape

(192,)

# Logistic Regression - Model 1

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

##Fit the Model

In [36]:
logreg = LogisticRegression(max_iter=100,C=2.0)
logreg.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=2.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

## Predict and accuracy for the train data

In [37]:
y_pred = logreg.predict(x_train)
print('Accuracy of logistic regression classifier on train set: {:.2f}'.format(logreg.score(x_train, y_train)*100))

Accuracy of logistic regression classifier on train set: 86.46


## Confusion matrix for train data

In [38]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_pred)
print(cm)

[[81 13]
 [13 85]]


## Predict and accuracy for the test data

In [39]:
y_pred = logreg.predict(x_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(x_test, y_test)*100))

Accuracy of logistic regression classifier on test set: 77.08


##Confusion matrix for test data

In [40]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[21  5]
 [ 6 16]]


# XGB Classifier - Model 2

In [41]:
#Train the model
model=XGBClassifier()
model.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

## Predict the train data

In [42]:
y_pred=model.predict(x_train)
print(accuracy_score(y_train, y_pred)*100)

100.0


## Confusion matrix for train data

In [43]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_pred)
print(cm)

[[94  0]
 [ 0 98]]


## Predict the test data

In [44]:
y_pred=model.predict(x_test)
print(accuracy_score(y_test, y_pred)*100)

79.16666666666666


## Confusion Matrix for test data

In [45]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[23  3]
 [ 7 15]]


##Train the model with tuning

In [46]:
model=XGBClassifier(learning_rate=0.1,max_depth =4, verbosity=2)
model.fit(x_train,y_train)

[16:24:26] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 16 extra nodes, 0 pruned nodes, max_depth=4
[16:24:26] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 14 extra nodes, 0 pruned nodes, max_depth=4
[16:24:26] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 14 extra nodes, 0 pruned nodes, max_depth=4
[16:24:26] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 14 extra nodes, 0 pruned nodes, max_depth=4
[16:24:26] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 16 extra nodes, 0 pruned nodes, max_depth=4
[16:24:26] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 16 extra nodes, 0 pruned nodes, max_depth=4
[16:24:26] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 14 extra nodes, 0 pruned nodes, max_depth=4
[16:24:26] INFO: /workspace/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 14 extra nod

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=4,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=2)

In [47]:
y_pred=model.predict(x_test)
print(accuracy_score(y_test, y_pred)*100)

85.41666666666666


### Logistic Regression accuaracy : 77.08 %
### XGBoost accuracy : 85.41 %